Use latest bake_action API.
As of blender 2.80, bake action takes an iterable `frames` argument
instead of frame_start, frame_end, and frame_step.

Compare
https://docs.blender.org/api/master/bpy_extras.anim_utils.html?highlight=bake_action#bpy_extras.anim_utils.bake_action
to
https://docs.blender.org/api/2.79b/bpy_extras.anim_utils.html?highlight=bake_action#bpy_extras.anim_utils.bake_action

Resolves #131:

```
TypeError: bake_action() missing 1 required keyword-only argument: 'frames'
```